### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by lagerweijgr**
I changed the read me

### CODE REVIEW

**Comment by lagerweijgr** [comment]
And I changed the validation toml file. First I made an new version but then I realized that I just could change version2 and that the additions would be added (that prevents problems because of a new version). 
However, I do not know if I have made the right pull request / changes because I see that my branch "lagerweijgr-patch-1" has conflicts.

**Comment by chStaiger** [comment]
The PR looks good. There is just one thing, since I merged my branch after you created this branch we have now a merge conflict. If you click on "Resolve conflicts" you will see that there are two versions for the _validation_schema_v2.toml. 
Everything from `<<<<<<< lagerweijgr-patch-1` till `=======` is the content of your branch, the rest till `>>>>>>> main` contains the current version. 

You can simple delete the rows and the markers in the browser to have a cleaned up version and then we merge.

**Comment by lagerweijgr** [comment]
All right. I have deleted the conflict markers, and I think it is fine.

**Review by chStaiger — APPROVED** [review]
I quickly added the correct types to all ID columns.

**Pull request merged**
